version: '3.7'

services:
  mysql:
    container_name: short_url_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=short_url
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - short_url_network

networks:
  short_url_network: